sudo: false
branches:
  only:
    - master
addons:
  apt:
    packages:
      - doxygen
script:
  - doxygen config/Doxyfile
notifications:
    email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: example/dist/html
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
