dist: xenial
sudo: false
branches:
  only:
    - master
install:
  - sudo apt-get install graphviz doxygen default-jre
  - curl -L https://sourceforge.net/projects/plantuml/files/plantuml.1.2019.5.jar/download -o /tmp/plantuml.jar
before_script: cd example
script:
  - doxygen config/Doxyfile
notifications:
    email: false
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: example/dist/html
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  target_branch: gh-pages
  on:
    branch: master
